// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "explorer_web.h"

// CExplorer_web

IMPLEMENT_DYNCREATE(CExplorer_web, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CExplorer_web properties

/////////////////////////////////////////////////////////////////////////////
// CExplorer_web operations
